Initial commit mobile repo
KrispyTech/airneis pull request #4
Opened 2024-01-07 17:12 UTC by hallycsse

2024-01-07 17:26 UTC, BarnabePILLIAUDIN requested changes
Can you please install and:
- nativewind
- eslint 
- prettier

And can you also remove default images and replace them by our logo

2024-01-08 17:46 UTC, BarnabePILLIAUDIN requested changes
@hallycsse 
Was not able to launch app
and add npm i step to the doc

2024-01-08 19:06 UTC, BarnabePILLIAUDIN reviewed
Removes the lines if they are not mandatory please

2024-01-08 19:06 UTC, BarnabePILLIAUDIN commented on mobile/app.json
> +    "web": {
Is this line mandatory
If not can you please remove it

2024-01-08 19:06 UTC, BarnabePILLIAUDIN commented on mobile/app.json
> +      "favicon": "./assets/favicon.png"
Is this line mandatory
If not can you please remove it

2024-01-08 19:06 UTC, BarnabePILLIAUDIN commented on mobile/app.json
> +    }
Is this line mandatory
If not can you please remove it

2024-01-14 21:57 UTC, Magali-D approved these changes

2024-01-15 14:36 UTC, BarnabePILLIAUDIN approved these changes
LGTM!

2024-01-15 14:37 UTC, merged