Airneis 43:  Database migration
KrispyTech/airneis pull request #47
Opened 2024-02-20 13:09 UTC by cedricgautier

2024-02-20 13:49 UTC, barnabepilliaudin commented on docker-compose.yml
> +    environment:
Should the db be moved to the dev docker-compose. As we will be using neon for production ?

2024-02-20 14:55 UTC, BarnabePILLIAUDIN approved these changes
LGTM!

2024-02-20 14:56 UTC, Magali-D commented on back/config/db.go
> +	log.Info("Database has been loadedddd")
```suggestion
	log.Info("Database has been loaded")
```

2024-02-20 14:56 UTC, Magali-D approved these changes

2024-02-20 14:57 UTC, Magali-D commented
Working on my side

2024-02-20 15:08 UTC, KyDev25 requested changes
We forgot to add a field to determine the display priority for products in a category.

2024-02-20 15:08 UTC, KyDev25 commented on back/model/Product.go
> +	ProductImages           []ProductImage `json:"productImages" gorm:"many2many:images_of_products"`
```suggestion
        OrderOfPriority           int                     `json:"orderOfPriority"`
	ProductImages           []ProductImage `json:"productImages" gorm:"many2many:images_of_products"`
```

2024-02-20 16:08 UTC, KyDev25 approved these changes

2024-02-20 16:09 UTC, merged

2024-04-07 17:01 UTC, avetisk commented on back/config/config.go
> +		log.Info("Production Environment has been loaded")
Where's my early return? 🤔