AIRNEIS-58-category-WEB
KrispyTech/airneis pull request #67
Opened 2024-03-04 20:32 UTC by hallycsse

category page :
![image](https://github.com/KrispyTech/airneis/assets/104196808/37abd330-66c3-4c94-8ab6-c0acaac86dc5)

Only front, as seen with @KyDev25 api/filter will be done later.

2024-03-04 20:47 UTC, cedricgautier commented on front/src/pages/categories/[categoryId].jsx
> +  description: "LES SALONS ÉCOSSAIS OFFRENT UNE POSSIBILITÉ INFINIE À VOTRE MAISON. DÉCOUVREZ LA DOUCEUR ET LA FRAÎCHEUR DE VOTRE FUTUR SALON."
Can you make a constants file for this

2024-03-04 20:53 UTC, cedricgautier commented
Can you specify the meaning of only  having only front ?

2024-03-04 20:55 UTC, hallycsse commented on front/src/pages/categories/[categoryId].jsx
> +  description: "LES SALONS ÉCOSSAIS OFFRENT UNE POSSIBILITÉ INFINIE À VOTRE MAISON. DÉCOUVREZ LA DOUCEUR ET LA FRAÎCHEUR DE VOTRE FUTUR SALON."
Only here to be replaced in the futur by the api call so does i really need to make a file for it.

2024-03-04 20:55 UTC, cedricgautier commented on front/src/components/Header.jsx
> +    {page !== "backoffice" ? (
magic number, please make constant

2024-03-04 20:56 UTC, hallycsse commented
only front signifying here than the page does not work with api call and it will be an other ticket work

2024-03-04 20:56 UTC, hallycsse commented on front/src/components/Header.jsx
> +    {page !== "backoffice" ? (
py-3 and text-4xl ?

2024-03-04 21:00 UTC, cedricgautier commented on front/src/pages/categories/[categoryId].jsx
> +  description: "LES SALONS ÉCOSSAIS OFFRENT UNE POSSIBILITÉ INFINIE À VOTRE MAISON. DÉCOUVREZ LA DOUCEUR ET LA FRAÎCHEUR DE VOTRE FUTUR SALON."
Okay sounds good, thanks

2024-03-04 21:01 UTC, cedricgautier commented on front/src/components/Header.jsx
> +    {page !== "backoffice" ? (
"backoffice"

2024-03-04 21:01 UTC, cedricgautier commented on front/src/components/Header.jsx
> +    <Link href="/" className="text-xl md:text-4xl py-3 font-extrabold">
Can you make a routes file and add the Home directory, thanks

2024-03-04 21:04 UTC, cedricgautier approved these changes
Few changes, but looks good to me.

2024-03-13 19:47 UTC, BarnabePILLIAUDIN requested changes

2024-03-13 19:47 UTC, barnabepilliaudin commented on front/src/components/ProductCard.jsx
> +    <Image alt="#" src={product.image} width={450} height={200} className="rounded-sm drop-shadow-box" />
Can you put product name as description for SEO purpose

2024-03-13 19:47 UTC, barnabepilliaudin commented on front/src/pages/categories/[categoryId].jsx
> +      <button className="w-full h-1/4 sm:h-1/3 bg-[url('https://picsum.photos/1800/350')] bg-center flex items-center justify-center">
Why having a Button here ?

2024-03-17 09:49 UTC, hallycsse commented on front/src/components/ProductCard.jsx
> +    <Image alt="#" src={product.image} width={450} height={200} className="rounded-sm drop-shadow-box" />
I don't understand what u mean by product name as description can u explain it pls

2024-03-18 12:30 UTC, BarnabePILLIAUDIN commented on front/src/components/ProductCard.jsx
> +    <Image alt="#" src={product.image} width={450} height={200} className="rounded-sm drop-shadow-box" />
Explained via discord DM

2024-03-24 16:57 UTC, Magali-D commented on front/src/components/ProductCard.jsx
> +    <Image alt="#" src={product.image} width={450} height={200} className="rounded-sm drop-shadow-box" />
Is the change satisfying?

2024-03-24 19:05 UTC, BarnabePILLIAUDIN approved these changes

2024-03-24 19:11 UTC, merged