Airneis 74 : Linter configuration for GoSec
KrispyTech/airneis pull request #73
Opened 2024-03-17 15:55 UTC by cedricgautier

2024-03-17 17:18 UTC, BarnabePILLIAUDIN requested changes
Please remove comments for unused rules

2024-03-17 18:24 UTC, cedricgautier commented
> Please remove comments for unused rules

Updated, thanks

2024-03-17 18:25 UTC, BarnabePILLIAUDIN approved these changes

2024-03-18 11:01 UTC, hallycsse reviewed
Good work

2024-03-18 11:02 UTC, hallycsse approved these changes

2024-03-18 11:02 UTC, merged