AIRNEIS-106: Frontend translations + doc
KrispyTech/airneis pull request #81
Opened 2024-03-22 14:38 UTC by BarnabePILLIAUDIN

# DEPENDENCIES (optional)

# DONE 

Made translation for frontend  

# TEST

- Do a `make dev` and go to `/`

2024-03-22 15:33 UTC, KyDev25 approved these changes
I've tested it and it works very well, very good job. As far as the doc is concerned, everything works for me, which is understandable.

2024-03-23 19:04 UTC, cedricgautier requested changes

2024-03-23 19:04 UTC, cedricgautier commented on front/public/locales/en/common.json
> +    "linkExample": "Exemple de lien"
Can you please fix the translation, if not mistaken it's supposed to be in English.

2024-03-23 19:04 UTC, cedricgautier commented on front/public/locales/fr/common.json
> +    "selectALanguage": "Séléctionnez une langue",
```suggestion
    "selectLanguage": "Séléctionnez une langue",
```

2024-03-24 19:18 UTC, cedricgautier approved these changes

2024-03-24 19:24 UTC, merged

2024-04-07 18:37 UTC, avetisk commented on front/src/components/Header.jsx
> +            <select className="bg-secondary " onInput={({ target: { value } }) => changeLocale(value)}>
Handlers should be declared outside of JSX.